### ISSUE TITLE
[Bug] Several issues with dispenser rules

### ISSUE THREAD

**Issue by manyrandomthings** [gnembon/carpet-extra#102]
dispenserPlacesBlocks:
* Several items such as torches, sea pickles, turtle eggs, seeds, doors, tall grass, string, and redstone dust are both placed and dispensed as an item at the same time (probably more but I didn't test everything)
* Plays a stone placing block sound even if the position is invalid (example: saplings with an invalid block below)
* Can't place chests (although it does work with trapped chests)
* Can't place hoppers/chests/furnaces if dispensersFillMinecarts is enabled even if no minecart is in front
* Creates water from air if seagrass or kelp is placed
* Doesn't update blocks that are powered by redstone when placed (such as redstone lamps)

dispensersFeedAnimals:
* Doesn't feed baby animals to grow them slightly
* Warped fungus doesn't feed striders (1.16)

dispensersMilkCows:
* ~~Doesn't appear to work at all~~ (working as of 1.16.3)
* This should probably also work with mooshrooms and stew
* Milk bucket is destroyed if dispenser is full

dispensersToggleThings:
* Doesn't toggle redstone dots/crosses (1.16)
* ~~Doesn't toggle trapdoors, doors, fence gates, etc~~ (WAI but rule description still mentions this works)

**Comment by ImUrX** [comment]
i removed trapdoors, doors, fence gates because they are already possible in redstone, i removed bells in the new one too

**Comment by manyrandomthings** [comment]
> dispenserToggleThings: i removed trapdoors, doors, fence gates because they are already possible in redstone

Alright but the rule description still imply that it's possible to toggle doors and such

https://github.com/gnembon/carpet-extra/blob/018a7073f0d6b6f3fa82405d9cf073ca4fdcd693/src/main/java/carpetextra/CarpetExtraSettings.java#L123

**Comment by ImUrX** [comment]
oh yeah i forgot i kept it like that

**Comment by Yttiricon** [comment]
I believe coral fans are another item that is both placed and dropped as an item

**Comment by torzod** [comment]
cocoa beans are also placed and dropped, consuming 2 items (at least it doesn't allow for duplication)

**Comment by RamsaKd** [comment]
Carpets can't be placed by dispensers.

**Comment by Megaminx12** [comment]
Glowstone can't be placed according to another issue.

**Comment by DeadlyMC** [comment]
Im working on fixing the issues, all should be good in the upcoming release

**Comment by DeadlyMC** [comment]
Also just tested `dispensersMilkCows` works perfectly fine, idk what u r on about @manyrandomthings

**Comment by manyrandomthings** [comment]
> Also just tested `dispensersMilkCows` works perfectly fine, idk what u r on about @manyrandomthings

That seems to be working now but it was broken in 1.16-pre2 when I made this bug report

**Comment by DeadlyMC** [comment]
All the issues should be looked after in the next release, this issue can be closed now
