### ISSUE TITLE
Dispensers placing coral in flowing water does not create source blocks

### ISSUE THREAD

**Issue by Yttiricon** [gnembon/carpet-extra#104]
When a dispenser (in any orientation) places a coral in flowing water, it places it as its non-waterlogged variant, meaning it cannot grow (using carpet renewableCoral)
![2020-06-24_18 31 06](https://user-images.githubusercontent.com/59745661/85833206-425cc500-b789-11ea-94c4-9c265b462ba3.png)
![2020-06-24_18 31 23](https://user-images.githubusercontent.com/59745661/85833208-44268880-b789-11ea-8f6c-0bf5fa9013d0.png)

**Comment by Yttiricon** [comment]
Through further testing, this behaviour appears to be locational

**Comment by DeadlyMC** [comment]
Should be fixed in upcoming release
