### ISSUE TITLE
[Suggestion] alternate renewableBlackstone using randomticks

### ISSUE THREAD

**Issue by Starmute** [gnembon/carpet-extra#105]
Blackstone in vanilla mc is of course non-renewable. But carpet-extra’s existing renewable blackstone feature feels cheaty, especially given the rarity of blackstone in vanilla. I would like to request an alternative renewableBlackstone in carpet-extra that works randomtick-based, similarly to renewableLava.

Essentially - Lava next to blue ice, when randomticked, has a chance to convert to blackstone, multiplied by the number of gilded blackstone blocks it's touching.

This would actually require some innovation regarding farm layouts as opposed to the existing blackstone generator in carpet-extra which is quite trivial to use.

Also it would give the rare gilded blackstone block a practical use (as the catalyst for the lavs’s solidification) and give players a reason to explore and find it.

**Comment by altrisi** [comment]
Do you think this is still needed/useful, given that blackstone is already renewable in vanilla?
If not, please close this issue to keep the issue tracker clean. If yes, please comment in here.
Thanks!
