### ISSUE TITLE
bonemeal interactions: kelp, sugarcane, cactus

### ISSUE THREAD

**Issue by aria1th** [gnembon/carpet-extra#108]
in 20w13a there was kelp growth not limited to one height, but it's fixed. It was not feasible enough to get bonemeal back, but it was one probability to get new source of fuels. It'd be great if we have kelpbonemealgrowthlimit rules.

And, just adding sugarcane interaction with bonemeal would be great too.

**Comment by Megaminx12** [comment]
https://www.curseforge.com/minecraft/mc-mods/vanilla-experience for better bonemeal.

**Comment by Megaminx12** [comment]
Added to carpet extra now (version 1.4.14), please close.
