### ISSUE TITLE
[Bug] Obsidian can be mined with non-diamond tools

### ISSUE THREAD

**Issue by alexpostovskiy** [gnembon/carpet-extra#112]
Obsidian can be mined with all non-diamond tools, including by hand, in 1.16.1 / carpet-extra 1.4.0. This does not seemingly apply to other blocks, such as diamond ore with a wooden pickaxe. This is present with all carpet-extra features on default, but is not present when the mob is removed.

**Comment by javiersalcedo** [comment]
Came here to post this. Obsidian is also mined faster (about 3x) that the wiki says it should be destroyed by each tool bellow diamond level.

**Comment by altrisi** [comment]
This is caused by a change in vanilla code in 1.16 for block registrations, that kind-of conflicts with the renewableLava Mixin.

**Comment by altrisi** [comment]
Fixed in #115 @ 3544257
For some reason it didn't autoclose the issue.
It can be closed now.
