### ISSUE TITLE
blockStateSyncing causes dropper and dispenser to be not able to respond to 4gt clock

### ISSUE THREAD

**Issue by Fallen-Breath** [gnembon/carpet-extra#113]
When rule `blockStateSyncing` is set to true, dropper and dispenser cannot respond to a 4gt clock. They will only get triggered every 8gt

How to reproduce:

1. build this setup or something
![image](https://user-images.githubusercontent.com/28978806/89415584-a39b8f00-d75e-11ea-8f10-3db887d95ce0.png)
2. flip the lever to create a 4gt clock, the dropper will get triggered every 4gt (expected behavior)
3. `/carpet blockStateSyncing true`
4. the dropper will get triggered every **8gt** (wrong behavior). You can put some items in the dropper to see item popping out every 8gt to make sure it's not a client desync

Environment:
- Minecraft 1.16.1
- Fabric loader 0.8.8+build.202
- Carpet mod 1.4.0
- Carpet Extension 1.4.0

**Comment by gnembon** [comment]
https://github.com/gnembon/carpet-extra/commit/4773f348e787bd7ce5203c7f7c01305d018bd50f
