### ISSUE TITLE
What does doubleRetraction do?

### ISSUE THREAD

**Issue by CollidaCube** [gnembon/carpet-extra#114]
When i enable doubleRetraction, all i notice different is that when pistons retract, there are some particles. What is it supposed to do?

**Comment by DeadlyMC** [comment]
It fixes https://bugs.mojang.com/browse/MC-88959, checkout the bug report it explains it well

**Comment by altrisi** [comment]
Closing this as it's a question that has been resolved (or at least no further questions were made).
