### ISSUE TITLE
Shulker Boxes Don't Stack In Inventories With New 1.4.14 Carpet Rule

### ISSUE THREAD

**Issue by Megaminx12** [gnembon/carpet-extra#141]
How to reproduce:

1) Turn on in tweakeroo, keep off in carpet
2) Observe how it works to see how it is supposed to work
3) Turn off in tweakeroo and turn on in carpet
4) Observer that the carpet rule does nothing and shulkers don't stack

**Comment by DeadlyMC** [comment]
I just tested it, it seems to work...maybe some conflict with tweakeroo? Could u send ur latest.log file

**Comment by Megaminx12** [comment]
I replaced every appearance of my Minecraft username with "Player_name" so that ppl don't know my MC username.

[latest.log](https://github.com/gnembon/carpet-extra/files/5433743/latest.log)

**Comment by Megaminx12** [comment]
The errors are just datapack errors that I'm fixing rn, don't worry about them.

**Comment by gnembon** [comment]
I can see there hopper optmizations, I can see actable, I can see lithium - anything could have yought the hook points for that.

**Comment by Megaminx12** [comment]
Should I try to find which mod is incompatible and let you know, or just ignore it? Tweakeroo's version still works so I still have access to the feature.

**Comment by DeadlyMC** [comment]
I think ive found the issue: https://github.com/maruohon/tweakeroo/blob/fabric_1.16_snapshots/src/main/java/fi/dy/masa/tweakeroo/mixin/MixinItemStack.java#L18-L22 ...i mean it should have been obvious ig, but both the mods inject at head and return new stack limits. In this case im confused which of the 2 mixins actually gets injected first, looks like tweakeroo wins and hence we never reach the carpet mixin. 
I think @maruohon added the rule as per someone's request? that someone thinks tweakeroo is too cheaty?

**Comment by maruohon** [comment]
Oh what... that's definitely a bad Mixin in Tweakeroo, as it always modifies the value. It should definitely be checking the tweak status there before canceling and returning the new value. I'll need to fix that.

**Comment by DeadlyMC** [comment]
Yeah i noticed it does that in all minecraft versions :P

**Comment by Megaminx12** [comment]
Thanks! I'm closing the issue now.
