### ISSUE TITLE
Server crashing duplication glitch with CtrlQCraftingFix and AutoCraftingTable

### ISSUE THREAD

**Issue by Wat86** [gnembon/carpet-extra#15]
Whenever using CtrlQCraftingFix's feature of fixing stack dropping in the crafting table while the carpet rule AutoCraftingTable is also enabled it creates an issue that causes for the item to be infinitely crafted without consuming items from the crafting table properly, causing for multiple thousand items to be dropped on the ground, crashing the game/server almost instantly.

The glitch can be recreated by:
Having carpet rule CtrlQCraftingFix set to true,
Having carpet rule AutoCraftingTable set to true
Holding down CTRL+Shift+Q while attempting to craft any item inside of a crafting table.

Video of glitch in action:
https://drive.google.com/file/d/1zNZBP6_40epvVPss54OW4ScloU7UoMe5/view

**Comment by gnembon** [comment]
tough cookie. Thankfully they work with the other one turned off, and you probably only need one at a time (either crafting stuff yourself, or via machine), yet still needs investigation.

**Comment by gnembon** [comment]
fixed in fabric-carpet v1.2.3
