### ISSUE TITLE
[Feature Request] The ability for dispensers to interact with flower pots.

### ISSUE THREAD

**Issue by enteranewusernamechangemyusername** [gnembon/carpet-extra#151]
I think it would be nice if there was a rule with a name like dispensersPotPlants which allows dispensers to add and remove plants from flower pots. Currently, only the player can add and remove flowers.
It would be very useful if it is also compatible with flowerPotChunkLoading because flower pots have the downside of not being togglable, and nether portals are not possible in the end and have the chance to break on restarts. Even though with current chunk loading mechanics it is impossible to use a single wire to load something far away, it would at least be useful for toggling chunk loading of a specific chunk that needs to be togglable (such as a mob switch) or using a mod like chonk to be able to remotely load chunks without the use of nether portals.
Adding this feature would make #61 possible if movableBlockEntities and dispensersPlaceBlocks are used.

**Comment by gnembon** [comment]
https://github.com/gnembon/carpet-extra/pull/212
