### ISSUE TITLE
[Feature Request] "No Slime Chunks" Rule

### ISSUE THREAD

**Issue by Philipp766** [gnembon/carpet-extra#161]
It would be a nice addition if there was a rule to disable Slime Chunks (maybe even on a chunk basis)
But I dont know if something like that is even possible from a code standpoint

**Comment by DragonEggBedrockBreaking** [comment]
in addition to this

make the rule name `slimeChunks`, and make the options `true` (default; vanilla behaviour), `false` (no slime chunks) and `all` or smth (every chunk is a slime chunk)

**Comment by DragonEggBedrockBreaking** [comment]
or you could add `slimeChunksDistribution`, and make it a percentage of all chunks

i.e. 0 is no slime chunks, 100 is every chunk is a slime chunk, etc.

if the vanilla distribution percentage is selected, idk what it is, then the feature should be disabled therefore not changing vanilla slime chunk locations

**Comment by RubixDev** [comment]
I added `slimeChunkPercentage` to [my extension mod](https://github.com/RubixDev/fabric-rug/releases/tag/v1.1.2) now, because I ran out of own ideas

**Comment by Philipp766** [comment]
thank you! this will be very helpful for underground bases.
