### ISSUE TITLE
Bug MC-153230

### ISSUE THREAD

**Issue by JASMein03M** [gnembon/carpet-extra#165]
This mod reintroduces bug [MC-153230](https://bugs.mojang.com/browse/MC-153230). This was fixed in 1.16.2 but if you use the latest version of this mod in 1.16.5 the bug is still there.

**Comment by Boobies** [comment]
I cannot reproduce this at all. My suspicion was that the op was running an older version without realizing it.

**Comment by DragonEggBedrockBreaking** [comment]
Try reproducing using the latest versions of fabric carpet and carpet extra
