### ISSUE TITLE
[Bug] Breaks Ilamngo's UTF on server

### ISSUE THREAD

**Issue by JASMein03M** [gnembon/carpet-extra#167]
When I use this mod on my server Ilmango's Universal Tree Farm will break. I don't really know why, I think it has something to do with the timings. And the thing that breaks at first, I think, are the pistons that push down the blocks into one stream.

**Comment by replaceitem** [comment]
Which rules do you have enabled?

**Comment by JASMein03M** [comment]
Only accurateBlockPlacement.

**Comment by DragonEggBedrockBreaking** [comment]
Ilmango's UTF doesn't work in 1.16+, he made a video on how to fix it.

**Comment by JASMein03M** [comment]
Yeah, I did the fixes. And I only think this mod breaks it because if I don't use this mod on my server the farm works totally fine.

**Comment by altrisi** [comment]
Closing this given it's been inactive for a while and carpet extra shouldn't be changing behaviour by default, but if you think it's still an issue feel free to comment and I'll reopen it, or make a new issue.
