### ISSUE TITLE
[Suggestion] dragonDropFullXP

### ISSUE THREAD

**Issue by Neubulae** [gnembon/carpet-extra#171]
or dragonDropXPPercentage
every time we kill dragon it only drops xp worth 0→14 which is :hmpf:

**Comment by RubixDev** [comment]
I dared to steal the idea and added that to the latest release of [my carpet extension mod](https://github.com/RubixDev/fabric-rug/releases/tag/v1.1.2) as `dragonXpDrop`

**Comment by DragonEggBedrockBreaking** [comment]
> or dragonDropXPPercentage
> every time we kill dragon it only drops xp worth 0→14 which is :hmpf:

So should this be closed?

**Comment by Neubulae** [comment]
> > or dragonDropXPPercentage
> > every time we kill dragon it only drops xp worth 0→14 which is :hmpf:
> 
> So should this be closed?

Prorobrobaly
