### ISSUE TITLE
1.16.5 Version??

### ISSUE THREAD

**Issue by pjlasl** [gnembon/carpet-extra#172]
Are their any plans to upgrade this to 1.16.5 so that it will work with Carpet?

**Comment by altrisi** [comment]
The [latest release](https://github.com/gnembon/carpet-extra/releases) explicitly states that it supports 1.16.5.

**Comment by pjlasl** [comment]
Apologies. I was on curseforge and the latest version available is for 1.16.2.
I have downloaded 1.16.5 :)

**Comment by DragonEggBedrockBreaking** [comment]
Maybe close the issue report now?
