### ISSUE TITLE
renewableIce rule doesn't work

### ISSUE THREAD

**Issue by reszon92** [gnembon/carpet-extra#176]
Tried to use renewable ice rule to convert to blue ice like Ilmango showd on his video and it doesn't seem to work in the newest version.

**Comment by DragonEggBedrockBreaking** [comment]
The feature used is not the one here. The one used is in https://github.com/DeadlyMC/QuickCarpet114. This issue is invalid as far as I can see.

**Comment by Boobies** [comment]
carpet-extra has had a rule called renewablePackedIce for a long time, where anvils falling on ice result in packed ice, and that works just fine as far as I can test. What rule did you use, what did you try, and what was the expected behavior?

**Comment by gnembon** [comment]
Well, could see that coming.

wish the suggestion to cover new ice types would be suggested here, where this feature has always been.

Suggesting renaming to `renewableIce` and cover all other types.

**Comment by Boobies** [comment]
I think that's reasonable. I can't imagine someone wanting this feature only for packed or blue ice but not the other.
