### ISSUE TITLE
/carpet dispenserPlacesBlocks true is not working with hoppers

### ISSUE THREAD

**Issue by dojofemy** [gnembon/carpet-extra#18]
**Version:** carpet-extra-19w38b-1.0.8

Here is a video showing it:
https://streamable.com/2sk4x

I've tested this a few times in the newest 1.15 snapshot (19w38b) - and got a confirmation on discord that it is indeed a bug.

Hopefully it will get fixed soon.
- Submitted by FEMY

**Comment by dojofemy** [comment]
- Also doesn't work in the 1.14.4 version of carpet-extra.

**Comment by gnembon** [comment]
should be fixed already
