### ISSUE TITLE
emptyShulkerBoxStackAlways isnt working

### ISSUE THREAD

**Issue by Philipp766** [gnembon/carpet-extra#181]
I used this tweak once before, and it was working fine. now i wanted to use it again, and freshly cheated shulkerboxes arent stacking anymore. I tried it with and without the normal shulkerbox stacking tweak, but no luck.

**Comment by DragonEggBedrockBreaking** [comment]
> I used this tweak once before, and it was working fine. now i wanted to use it again, and freshly cheated shulkerboxes arent stacking anymore. I tried it with and without the normal shulkerbox stacking tweak, but no luck.

iirc, this rule conflicts with tweakeroo, so if you use tweakeroo (in singleplayer), just use the tweakeroo rule(s)
