### ISSUE TITLE
[Suggestion] Mobs can spawn on more blocks in nether fortresses

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [gnembon/carpet-extra#182]
As far as I know, mobs can spawn on any block inside the "smaller" nether fortress bounding box, which is why crossroads are so good for wither skeleton/general fortress mob farms. They can also spawn inside the "bigger" nether fortress bounding box (but outside the "smaller" one) if they spawn on nether brick. Nether brick has the following issues for wither skeleton farms (in my opinion):

- You cannot place wither roses on it. 
- It is a full block (I will explain this later)
- It is not slippery (like ice).

I have come up with a few different ways this could be implemented.

- The `moreFortressSpawningBlocks` rule (name is WIP). This allows fortress mobs to spawn on netherrack, soul sand, soul soil, packed/blue ice and gravel everywhere in the "bigger" bounding box. This would allow for wither rose farms, farms using soul sand to pick up items and allow for killing mobs with tnt looting, mobs using slime and packed ice (like your farm) and also a fun new concept of moving the spawning blocks around (if it is gravel).

- The `everyBlockFortressSpawnable` rule (name is also WIP). This allows mobs to spawn on any block, anywhere inside the fortress bounding box. This would allow for everything above, and also allow for some small but simple early game farms using just basic blocks (dirt, cobblestone, etc.)

- An alternate implementation of the `moreFortressSpawningBlocks` rule **(preferred implementation)**. This would simply have three options. False (vanilla behaviour) is default. `More` could be a second option, which allows for netherrack, soul sand, soul soil, packed/blue and gravel. 'All' could be every block is spawnable. This would be basically a combination of both previous implementations I suggested.

**Comment by RubixDev** [comment]
Implemented that in [the latest Rug release](https://github.com/RubixDev/fabric-rug/releases/tag/v1.1.2) with some more blocks in the 'more' category

**Comment by DragonEggBedrockBreaking** [comment]
> Implemented that in [the latest Rug release](https://github.com/RubixDev/fabric-rug/releases/tag/v1.1.2) with some more blocks in the 'more' category

Thanks
