### ISSUE TITLE
[Suggestion] oldFloatingSand

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [gnembon/carpet-extra#185]
Add new rule `oldFloatingSand` which re-adds the 1.12 behaviour of making floating sand with two tall flowers. The simple boolean values `true` and `false` will of course be enough.

**Comment by RubixDev** [comment]
Also added that to [Rug](https://github.com/RubixDev/fabric-rug/releases/tag/v1.1.3) now as `tallPlantNoUpdate`

**Comment by DragonEggBedrockBreaking** [comment]
> Also added that to [Rug](https://github.com/RubixDev/fabric-rug/releases/tag/v1.1.3) now as `tallPlantNoUpdate`

Thanks
