### ISSUE TITLE
I almost don't want this fixed: Clerics can warm nether farts.

### ISSUE THREAD

**Issue by mlv** [gnembon/carpet-extra#191]
In the README, it says: Clerics can warm nether farts.
Which sounds wonderful, but technically is a typo.

**Comment by DragonEggBedrockBreaking** [comment]
> In the README, it says: Clerics can warm nether farts.
> Which sounds wonderful, but technically is a typo.

As Gnembon has said in the past, this works as intended, please close.

**Comment by mlv** [comment]
Works as intended, to my joy
