### ISSUE TITLE
Incompatibility with Better Hoppers

### ISSUE THREAD

**Issue by srnyx** [gnembon/carpet-extra#200]
Refer to https://github.com/Flytre/hplus2/issues/3

**Comment by srnyx** [comment]
> Seems like that repository was deleted, is this still an issue? If so, do you have the crash reports?

I shut down my server a while ago so I'm not sure if it still occurs. You can just close this if you want.
The mod was https://www.curseforge.com/minecraft/mc-mods/hopper by the way.

**Comment by altrisi** [comment]
Makes sense, I'll close and it can be reopened if someone has issues in the future, thanks!
