### ISSUE TITLE
[Suggestion] renewableDeepslate

### ISSUE THREAD

**Issue by Shu-Dawei** [gnembon/carpet-extra#219]
Cobblestone Generators should turn into Deepslate (or Cobbled Deepslate) Generators when a special Block is placed below them (simillar to how Basalt Generators work).

**Comment by replaceitem** [comment]
This is already in carpet (normal carpet) and makes cobble generatord generate deepslate below Y<16

**Comment by Shu-Dawei** [comment]
Oh I'm sorry, I seem to have totally missed the release with that feature ...
Closing this Issue then ...
