### ISSUE TITLE
dragonEggBedrockBreaking rule does not work properly below y0 (1.17)

### ISSUE THREAD

**Issue by aria1th** [gnembon/carpet-extra#220]
How to reproduce:
use datapack (for example, CavesandCliffsPreview official datapack)

build some dragon egg dupers BELOW y0.
Turn on dragonEggBedrockBreaking rule.

-> dragon Eggs are not being pushed / pulled / falls / jumps.

![2021-07-11_02 38 54](https://user-images.githubusercontent.com/35677394/125171806-250e6380-e1f1-11eb-9943-8263f1f75a88.png)

Carpet version : 1.4.40 = carpet extra
Minecraft version : 1.17, can reproduce at 1.17.1+

note: y0bedrockbreaking does not affect this thing.

**Comment by gnembon** [comment]
Yeah, its not even part of carpet core, so transfering.

**Comment by gnembon** [comment]
I guess the report says confirmed in 1.4.40. 1.4.43 is only a version bump for carpet-extra

**Comment by altrisi** [comment]
No, there was #215.
