### ISSUE TITLE
[Suggestion] Option to have deepslate instaminable like stone when using a netherite pick

### ISSUE THREAD

**Issue by RightHandLeft** [gnembon/carpet-extra#229]
Add a rule for instamining deepslate like you can with stone, eff 5 diamind/netherite pickaxe, and haste 2 beacon.
Balance it a bit by requiring a netherite pick instead of a diamond pick.

**Comment by Ghoulboy78** [comment]
There's a scarpet app which adds this. If you're in the carpet discord you can ask there.

**Comment by altrisi** [comment]
Yes, `survival/instamine_deepslate.sc` (`/script download survival/instamine_deepslate.sc` or manual from <https://github.com/gnembon/scarpet/blob/master/programs/survival/instamine_deepslate.sc>)
