### ISSUE TITLE
Crash on launch while launching the game with the mod for the first time

### ISSUE THREAD

**Issue by Dualboi** [gnembon/carpet-extra#239]
The game crashes on launch while trying to install carpet mod extra along side carpet mod

other mods I have Installed are litematica, sodium, starlight, minihud, tweakeroo, and lithium
Any help would be appreciated

**Comment by replaceitem** [comment]
If you are using carpet (base  carpet, not extra) 1.4.54, you need to downgrade to 1.4.53.

If that's not the case, plese send the log  (.minecraft/logs/latest.log) here

**Comment by altrisi** [comment]
Going to close because of no response and no crash report to be able to find the issue, though feel free to open a new issue if it still happens.
