### ISSUE TITLE
Not compatible with the latest Towelette mod

### ISSUE THREAD

**Issue by Neubulae** [gnembon/carpet-extra#24]
https://pastebin.com/zLrAnAx1
This will show up.

**Comment by DeadlyMC** [comment]
Could u provide the whole log? I don't see anything related to carpet in that log

**Comment by sjackser** [comment]
> Could u provide the whole log? I don't see anything related to carpet in that log

https://pastebin.com/6MHJdw5j
sorry for not cutting the correct portion of it, this is the whole log.

**Comment by DeadlyMC** [comment]
@Virtuoel had potentially eliminated this issue in https://github.com/Virtuoel/Towelette/commit/b11256e81ae0466bd2d05f91a39e20ffa5b02837
I checked curseforge there i no new release with this code out atm. 

Also we will see if we can fix this issue from our side

**Comment by sjackser** [comment]
ok, thx!

**Comment by Virtuoel** [comment]
A fixed version of Towelette has been pushed to CurseForge.

**Comment by DeadlyMC** [comment]
Awesome :D , @sjackser could u try that version out

**Comment by sjackser** [comment]
The new version is incompatible with another mod

**Comment by DeadlyMC** [comment]
Another mod?

**Comment by sjackser** [comment]
which is called adorn

**Comment by gnembon** [comment]
can you provide the crash report like you have done before? We can't guarantee we can circumvent it, but sometimes it doesn't matter.

**Comment by Virtuoel** [comment]
They meant Adorn was not compatible with the new Towelette version, but that has since been fixed on Adorn's side. I believe this issue is resolved.

**Comment by ImUrX** [comment]
@gnembon this is long dead and closed i think lol

**Comment by Neubulae** [comment]
Holy sh<>t this is not closed yet?
