### ISSUE TITLE
Dragon Egg Bedrock Breaking

### ISSUE THREAD

**Issue by HighPotential1** [gnembon/carpet-extra#244]
carpet-extra-1.18-1.4.56
fabric-carpet-1.18-1.4.56+v211130

1.18.1 Fabric Server 

Having trouble getting the dragon egg bedrock breaking addition to work. I was able to load the extra and set both values to true; 

I tried several methods including manually activating in lazy chunk and activation upon lazy chunk detection but neither worked. Curious if it's due to differences between 18 and 18.1, something I am missing, etc. Thank you for any assistance.

**Comment by Drhampust** [comment]
I am facing the same problems, did you get it to work, and how?
