### ISSUE TITLE
1.18.2 Broken AccurateBlockPlacement

### ISSUE THREAD

**Issue by aria1th** [gnembon/carpet-extra#248]
ServerPlayerNetworkHandler now checks if all( HitVec - BlockPos center < 1).
Carpet Extra should mixin this to bypass check, or implement other way... now we can't use modified X values to tell server something.

**Comment by maltreuter** [comment]
I have this issue on my server when I try to use tweakeroo's flexibleBlockPlacementRotation.

output from server console:
```
Server thread/ Ignoring UseItemOnPacket from USERNAME: Location (-445.0, 69.0, 125.14848057925701) too far away from hit block class_2338{x=-451, y=69, z=125}.
```

fabric-carpet 1.4.66 v220228
carpet-extra  1.4.64

**Comment by JarheadHME** [comment]
This is the [commit](https://github.com/maruohon/tweakeroo/commit/d22ffe6f808ade701cf24d45eeeabd6c08e7026c) masa used to fix it in tweakeroo if it helps

**Comment by maruohon** [comment]
I have PRs prepared to fix this, and also to update the accurate placement implementation to use the same code as Tweakeroo does. I just need to still test it on a local server to make sure it works properly before I submit the PRs.

**Comment by MasteredRed** [comment]
I just want to ask. Did the issue with accurate placement ever get fixed?

**Comment by maruohon** [comment]
@MasteredRed The PRs are still open. There is a fixed build linked in this comment: https://github.com/gnembon/carpet-extra/pull/251#issuecomment-1075025541

**Comment by altrisi** [comment]
This issue has been fixed in latest release (note that it's not in curseforge because an error during release, but you can get it on github releases).
