### ISSUE TITLE
1.19.2 pls update

### ISSUE THREAD

**Issue by HiroDeveloper** [gnembon/carpet-extra#275]
Pls update to 1.19.2

**Comment by altrisi** [comment]
Doesn't the latest version already work on 1.19.2?

**Comment by JJSax** [comment]
> Doesn't the latest version already work on 1.19.2?

Yeah, for the most part.  I found a critical bug with it in 1.19.2 (#276).  But I can play with the latest version.

He is definitely working on the update though. cc63625c11bae10c5e160952b920ed74da139647

**Comment by altrisi** [comment]
I'll close this one then.
