### ISSUE TITLE
[Fabric 1.19.2] Conflict with Bedrockify mixins

### ISSUE THREAD

**Issue by Nekkok** [gnembon/carpet-extra#277]
The game crashes before loading. I've talked with the other mod's author and points to your mod. Here's my log:
[latest.log](https://github.com/gnembon/carpet-extra/files/9943554/latest.log)

**Comment by altrisi** [comment]
This is actually a conflict with bedrockify

**Comment by altrisi** [comment]
It has a _very_ similar mixin to ours, just protected instead of private for some reason.

**Comment by altrisi** [comment]
Weird thing is it looks like bedrockify disables it when carpet extra is enabled?

**Comment by altrisi** [comment]
As a workaround you could follow the steps in juancarloscp52/BedrockIfy#188.

**Comment by altrisi** [comment]
I'm going to close this as it should in theory be fixed in the latest version of bedrockify.
