### ISSUE TITLE
Shulker don’t stack to 16 with hoppers 

### ISSUE THREAD

**Issue by RuffleSteels** [gnembon/carpet-extra#299]
When you put shulker a in a chest and a hopper below, then inside the hopper, the shulkers stack to 64 even though i’ve set it to stack to 16. Or you can recreate it by feeding a hopper full of shulkers into a container.

**Comment by RuffleSteels** [comment]
Can this also be added for 1.19.4? that’s where I experienced the issue?

**Comment by altrisi** [comment]
You could backport the simple change [here](https://github.com/gnembon/carpet-extra/commit/5546a4e674875434f1239c86a9640b74e486b008) to the 1.19.4 branch and that should do it, Carpet Extra doesn't usually publish backports (lmk if you need any help)
