### ISSUE TITLE
Game crash when opening crafting table

### ISSUE THREAD

**Issue by Noxally** [gnembon/carpet-extra#30]
If the rule for autoCraftingTable is set to true, right clicking a crafting trable (with or without a held item) causes a crash. Crash report attatched.

This only happens using the latest 19w42a version of carpet-extras.
[crash-2019-10-17_13.07.11-client.txt](https://github.com/gnembon/carpet-extra/files/3738898/crash-2019-10-17_13.07.11-client.txt)

**Comment by gnembon** [comment]
thanks, should be fixed tomorrow

**Comment by Noxally** [comment]
Perfect, thanks for the great mod :D

**Comment by gnembon** [comment]
Sorry for the delay. Check version 1.1.3_2 (compatible with carpet 1.2.0) for a fixed crafting table.
