### ISSUE TITLE
accurateBlockplacement not working on fabric 1.19.4 server

### ISSUE THREAD

**Issue by iblamefabian** [gnembon/carpet-extra#307]
Hi,
I am running a Minecraft fabric 1.19.4 server on Bisect Hosting. I‘ve installed carpet mod, as well as carpet extra. Features like stackable Shulkerboxes work, but when I‘m trying to enable accurateBlockplacement, it does not work. For example when using Litematica, the blocks do not face the right way. Any ideas? Would appreciate the help :)

**Comment by sussyboiiii** [comment]
Same issue for me in 1.20.2, I also have enable the option on tweakeroo with no success.

**Comment by k3fabian** [comment]
Install carpet extra and set accurateBlockplacent to true. 

-open Litematica settings
-go to to the first tab on the left (general or generic idk)
-search for "protocol"
-an option "Easyplace protocol version" should appear
-set it to version 3

If you are having trouble I'll be happy to help.
