### ISSUE TITLE
1.21 Server crash with autoCraftingDropper=true

### ISSUE THREAD

**Issue by Zevac-ZSF** [gnembon/carpet-extra#326]
Hello, I'm prepping to upgrade my server to 1.21, and I currently have 200+ autoCraftingDropper modules across my world, I will ofcourse convert them all to use the new Crafter, but that will take time, so for now autoCraftingDropper not working is a big problem for me. Sadly as soon as I try to auto craft using autoCraftingDropper the server crashes. 

Attached is the log while I have only carpet and carpet extra as mods on the server, 
also removed all datapacks
no mods enabled on the client except Fabric loader
both server and client use OpenJDK 22.02.
[latest.log](https://github.com/user-attachments/files/16398929/latest.log)

Thanx in advance for your help :-)

Z.

**Comment by altrisi** [comment]
Sorry for the very late reply, but I found the issue and will be pushing a fixed version in a moment.

I think it's from a small optimization they made on 1.21 that Carpet Extra didn't adapt to.

**Comment by altrisi** [comment]
Fixed in fa4eec743faf3281b25ee8ae54b4c59ef4ae5376, fix in 1.4.148.

**Comment by Zevac-ZSF** [comment]
Thank you very much!
:-)
Z.

    On Friday, August 23, 2024 at 01:38:18 PM GMT+2, altrisi ***@***.***> wrote:  
 
 


Fixed in fa4eec7, fix in 1.4.148.
