### ISSUE TITLE
1.21.3 Support

### ISSUE THREAD

**Issue by TheUnknownCod3r** [gnembon/carpet-extra#332]
Update required for 1.21.3, tested using the Fabric Overrides to bypass version requirement, spits out the Mixin Error FlowerPotBlockMixin, about onActivate. Error Below:

`[16:58:46] [main/ERROR]: Mixin apply for mod carpet-extra failed carpet-extra.mixins.json:FlowerPotBlockMixin from mod carpet-extra -> net.minecraft.class_2362: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on onActivate could not find any targets matching 'Lnet/minecraft/class_2362;method_55765(Lnet/minecraft/class_1799;Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;)Lnet/minecraft/class_9062;' in net/minecraft/class_2362. Using refmap carpet-extra-refmap.json [INJECT_PREPARE Applicator Phase -> carpet-extra.mixins.json:FlowerPotBlockMixin from mod carpet-extra -> Prepare Injections -> handler$bae000$carpet-extra$onActivate(Lnet/minecraft/class_1799;Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_2680;)V -> Parse ->  -> Validate Targets]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onActivate could not find any targets matching 'Lnet/minecraft/class_2362;method_55765(Lnet/minecraft/class_1799;Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;)Lnet/minecraft/class_9062;' in net/minecraft/class_2362. Using refmap carpet-extra-refmap.json [INJECT_PREPARE Applicator Phase -> carpet-extra.mixins.json:FlowerPotBlockMixin from mod carpet-extra -> Prepare Injections -> handler$bae000$carpet-extra$onActivate(Lnet/minecraft/class_1799;Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_2680;)V -> Parse ->  -> Validate Targets]`

**Comment by TheUnknownCod3r** [comment]
Theres actually more wrong than just the one Mixin, but needs an update regardless.

**Comment by sakura-ryoko** [comment]
You can't force mods to work in newer than expected versions when code changes are needed.  See my PR, and try that out.

**Comment by TheUnknownCod3r** [comment]
> You can't force mods to work in newer than expected versions when code changes are needed. See my PR, and try that out.
> 
> #333

Never intended to force it, just wanted to see where the error lay so I could take a look, and at least let the devs know if they didn't already. Apologies if it came off that way. I'll make a copy of our server, and add the build to it in the morning, and let you know how it runs.

**Comment by sakura-ryoko** [comment]
Sounds good; it is freshly experimental, until proven, of course.

**Comment by TheUnknownCod3r** [comment]
Seems to work fine for me, although im only using Dispensers for Shears right now, so can't comment on anything dispenser related. I appreciate you taking the time to update, Sakura :)

**Comment by TheUnknownCod3r** [comment]
Closing since support has been up for a while, totally forgot this.
