### ISSUE TITLE
Dispensers place blocks does not plant crops on server

### ISSUE THREAD

**Issue by jusTinMan** [gnembon/carpet-extra#42]
Dispensers place blocks allows for planting crops on single player but not the server.

**Comment by DeadlyMC** [comment]
Could you provide more info, carpet version, mc version, etc. Some screenshots of the issue might help as well ig

**Comment by jusTinMan** [comment]
Server
OS: Debian
Minecraft: 1.15.1
fabric-carpet-1.15.1-1.3.2+v191230
carpet-extra-1.15-1.3.0
Fabric: 0.7.2+build.175

and tested in Fabric: 0.7.3+build.176



single player
OS: Windows 10
Minecraft: 1.15.1
fabric-carpet-1.15.1-1.3.2+v191230
carpet-extra-1.15-1.3.0
Fabric: 0.7.2+build.175

Not sure how the screen shots are going to help but the one with the sand is the server and the darker one is single player 

![2020-01-08_02 13 18](https://user-images.githubusercontent.com/10599893/71958018-41c17980-31bd-11ea-9b37-fc992d581b41.png)
![2020-01-08_01 57 35](https://user-images.githubusercontent.com/10599893/71958019-41c17980-31bd-11ea-956e-3cc89952fc34.png)

**Comment by gnembon** [comment]
tested with plain carpet + carpet-extra and it works. You may have other mods working as well that disable extra dispenser functionality. Please provide a list of mods used (on the server).

**Comment by DeadlyMC** [comment]
Have u tried with other blocks? I have a feeling you don't have the carpet-extra jar on the server

**Comment by jusTinMan** [comment]
The only mod we have on the server is carpet + carpet-extra. Placing other blocks is fine even saplings. We have this issue on 2 different servers.
I have an extra server I will try to wipe and reinstall carpet, carpet-extra, and fabric.  
![image](https://user-images.githubusercontent.com/10599893/72214807-83ad3100-34d7-11ea-97e8-51a9a3e69fbe.png)

**Comment by jusTinMan** [comment]
Just updated everything and it is good now. Thanks.

**Comment by jusTinMan** [comment]
Found out that you cant have dispensers feed animals and have the dispensers place blocks to plant carrots.
