### ISSUE TITLE
"dispensersFeedAnimals" stops "dispensersPlaceBlocks" from working with seeds

### ISSUE THREAD

**Issue by Shroototem** [gnembon/carpet-extra#49]
Minecraft - 1.15.2
Carpet-Extra-1.15.2-1.3.5

When you enable "dispensersFeedAnimals" it prevents "dispensersPlaceBlocks" from placing seeds on farmland. Instead the seeds are dispensed as items.

**Comment by ImUrX** [comment]
This would be a complete rewrite of how behaviours are added to dispenser, but if @gnembon isnt against redoing some things and have better communication with each behaviour, I will do it

**Comment by Shroototem** [comment]
Definitely don't stress about it. Just wanted to let you guys know about it.
