### ISSUE TITLE
[suggestion]Return the behavior of the comparator in 1.16 to previous 1.15

### ISSUE THREAD

**Issue by Harveykang** [gnembon/carpet-extra#50]
![f87c19e66df279f9006bcba1b991670d4cd8cecc png@518w_1e_1c](https://user-images.githubusercontent.com/46108547/74006977-2a420000-49b8-11ea-932d-b7fdfa48b405.png)
what's happened in 20w06a ...

**Comment by ImUrX** [comment]
Are you sure it will be permanent?

**Comment by altrisi** [comment]
This have been fixed in vanilla a while ago, and this issue probably should be closed...
