### ISSUE TITLE
[enhancement] Potted wither rose doesn't work as chunkloader for flying machines.

### ISSUE THREAD

**Issue by obesevran** [gnembon/carpet-extra#61]
I'd like to see a chunk loader moveable by pistons for tunnel bores and what not. the wither rose can't be moved and only loads one chunk so issues may occur with only part of flying machine in chunk. 

Other than that im loving the mod so much to say in favor of it, don't want to burden you with a list of features you're already aware of.

**Comment by Megaminx12** [comment]
A way to do that would be making flower pots pushable, and keeping their data.

**Comment by gnembon** [comment]
https://github.com/gnembon/carpet-extra/pull/212
