### ISSUE TITLE
[Feature request] [Survival] Hopper Jukeboxes

### ISSUE THREAD

**Issue by jedenastka** [gnembon/carpet-extra#63]
I suggest adding an option to Survival category to allow hoppers to insert discs into jukeboxes and, after finishing, to remove them too. Why? Cause why not - I want to play my music on loop :P I could find/make another mod for that (frick, I could probably even script this in scarpet), but Carpet is meant to be the one and only Vanilla enchancent mod you need, isn't it?
If it's too much for standard Carpet, consider adding it to Carpet Extra.

**Comment by bencrazyalchemist** [comment]
I think this idea would work better if you use a dropper or dispenser to put the disc in, just a suggestion.

**Comment by jedenastka** [comment]
> I think this idea would work better if you use a dropper or dispenser to put the disc in, just a suggestion.

MHO is that jukebox should act as a container. And you can put things into containers by using hoppers or droppers.

**Comment by ImUrX** [comment]
Isnt there a dispenser behaviour that does this?

**Comment by altrisi** [comment]
Yes, there is already `dispensersPlayRecords` that does exactly this, but with dispensers instead.
May this be closed? I don't think having two different methods of doing the same, at least in this case, would be really worth maintaining, and this issue is getting old.

**Comment by jedenastka** [comment]
Oh, okay. Fair point. I'm closing this.
