### ISSUE TITLE
[Suggestion] shulkerBoxesInShulkerBoxes

### ISSUE THREAD

**Issue by schuelermine** [gnembon/carpet-extra#64]
Allows putting shulker boxes into shulker boxes

**Comment by bencrazyalchemist** [comment]
I really like this idea, but I do believe that a client modification would be necessary also to do this.

**Comment by DeadlyMC** [comment]
We decided to not implement this feature, considering it could be really dangerous for worlds. Over compacting could potentially make your world unplayable. You only need to nest them like 3 or 4 times and the server already dies...

**Comment by rootinchase** [comment]
How about if we can put EMPTY shulker boxes (possibly stacked) inside a shulker box? 

They would have to be completely empty for it to work, it'd allow one to transport larger quantities of shulker boxes to their farms and such, but not be asking for trouble like if they could be filled.
![2020-03-23_23 44 57](https://user-images.githubusercontent.com/19437547/77389225-927a5480-6d60-11ea-9807-e3303e1de350.png)

**Comment by gnembon** [comment]
isn't stacking of empty shulkerboxes enough?
