### ISSUE TITLE
[Suggestion] Dispensers interact with cauldron

### ISSUE THREAD

**Issue by Minepig** [gnembon/carpet-extra#66]
Make dispensers to be able to interact with cauldron:

- Dispensers with a water **bucket** can fill the empty cauldron in front of it, returning a empty bucket. If the cauldron has some water nothing happens (just don't drop it plz).

- Dispensers with a water **bottle** can add one level of water to the cauldron in front of it, returning a empty bottle. If the cauldron is full nothing happens.

- Dispensers with a empty **bucket** can empty the fully filled cauldron in front of it, returning a water bucket (or drop it if there's no room). If the cauldron isn't full nothing happens.

- Dispensers with a empty **bottle** can remove one level of water from the cauldron in front of it, returning a water bottle (or drop it if there's no room). If the cauldron is empty nothing happens.

**Comment by felix91gr** [comment]
This would be super nice. The other day I wanted a compact T flip flop that I could toggle with an Observer's pulse, and this idea came to mind. It just makes sense, is basically just as compact as a piston TFF, and doesn't move blocks. Just plain nice ^^

**Comment by RubixDev** [comment]
This feature is already in [minitweaks](https://github.com/manyrandomthings/minitweaks) called `dispensersUseCauldrons`

**Comment by gnembon** [comment]
https://github.com/gnembon/carpet-extra/pull/212
