### ISSUE TITLE
[Suggestion] [Crazy Idea] Portable update suppressor

### ISSUE THREAD

**Issue by Minepig** [gnembon/carpet-extra#78]
When a Dragon Egg (or another rare special block) receives a NC-update, if a special condition is met, the dragon egg will throw a StackOverflowException in order to suppress the block update.

The special condition should be a little strict in order to prevent misoperation. For example:

- The Dragon Egg is powered by redstone from a certain surface (maybe the top surface).

- AND the Dragon Egg is sitting on a certain block. 

- AND the Dragon Egg is receiving a NC-update (not PP) from a Powered Rail (not other blocks).

**Comment by bencrazyalchemist** [comment]
While this idea seems fun too mess with, I suspect you will find more enjoyment in your game by building an actual update suppresor. If you want to make it easier though I do recommend lowering your jvm stack size to one half or one quarter via arguments. This allows you to make your update suppresor perpotionaly smaller.

**Comment by gnembon** [comment]
Already present in core carpet. Use `/carpet interactionUpdates false` for a simple update supressor.
