### ISSUE TITLE
[Suggestion] Dispensers should carve pumpkins (Would allow golem automation)

### ISSUE THREAD

**Issue by c47s** [gnembon/carpet-extra#80]
Essentially what it says on the tin. Would be nice to add an option, in the same vein as dispensersTillSoil and the vanilla dispenser flint-and-steel mechanics, to let dispensers carve pumpkins with shears. This would allow for fully automated snow golem factories in combination with autoCraftingDropper.

**Comment by bencrazyalchemist** [comment]
Yeah and it's not like there is already an in-game mechanic that can produce infinite iron golems.

**Comment by c47s** [comment]
Couldn't you use an iron farm, and just don't kill the spawned golems?
Or would their continued existence prevent further ones from spawning?

**Comment by Ghoulboy78** [comment]
you can just move them away and the villagers will spawn new ones
