### ISSUE TITLE
[REQUEST] Dispenser block placement whitelist/blacklist

### ISSUE THREAD

**Issue by supersaiyansubtlety** [gnembon/carpet-extra#81]
Pretty self explanatory. I'd like to be able to place anvils but not dirt, for example.

**Comment by gnembon** [comment]
if you don't put them into the dispenser it won't place, right?

**Comment by supersaiyansubtlety** [comment]
Sure, but what about on servers where you don't want to manually enforce things? 
And what about if you're feeding arbitrary items into a dispenser and don't want to have in-game sorters for every block you want to be placed?

**Comment by bencrazyalchemist** [comment]
I agree, this would be extremely nice.
