### ISSUE TITLE
[Suggestion] Axe in dispenser strips logs

### ISSUE THREAD

**Issue by supersaiyansubtlety** [gnembon/carpet-extra#86]
To continue with the right-clicking simulation of dispensers. 
Could make stripped log converters similar to concrete converters.

**Comment by bencrazyalchemist** [comment]
An AFK stripped log converter is a

**Comment by bencrazyalchemist** [comment]
AFK stripped log converters are easy already but I like this idea. I would recommend that feature be attached to dispensers with hoes tilling dirt and coarse dirt to make dirt farms easier, and dispensers with shovels turning grass blocks into paths. You could call it DispensersTransformBlocks.

**Comment by supersaiyansubtlety** [comment]
Personally, I'm always in favor of separate configs. 
I think the axe-log-stripping would just make the automation faster (I don't think you can place a log and strip it all within 4 game ticks?) and have less of the clunkiness of complicated AFK player interaction like replacing a broken axe. 
Can hoes already till coarse dirt to dirt? If not that also sounds like a good addition.

**Comment by Ghoulboy78** [comment]
can do with scarpet.

**Comment by supersaiyansubtlety** [comment]
Cool. Would still be useful to have it included in the mod.

**Comment by Ghoulboy78** [comment]
what point?

**Comment by supersaiyansubtlety** [comment]
For those that don't have the time or background to literally learn a new scripting language just to enable a single feature.

**Comment by Ghoulboy78** [comment]
no need. Only 1 person has to do it, then everyone else can copy into scripts folder. If you want I'll go do it later, then you can copy that and close this one.

**Comment by supersaiyansubtlety** [comment]
I mean, that's better, but for users who aren't me there's no good way for them to find out about this feature because it's not actually part of the mod. 
Don't bother making the script for my sake, I'm working on my own mod to configure dispensers that will have this functionality.

**Comment by gnembon** [comment]
https://github.com/gnembon/carpet-extra/pull/212
