### ISSUE TITLE
[Suggestion] carefulBreak

### ISSUE THREAD

**Issue by whoImT** [gnembon/carpet-extra#87]
It would be great if xcoms carefulBreak from carpetmod112 is also available in carpet-extra.

**Comment by gnembon** [comment]
what's careful break?

**Comment by whoImT** [comment]
when you break a block while sneaking the block directly goes in your inventory

**Comment by bencrazyalchemist** [comment]
That's a scarlet feature, see https://youtu.be/g7Ku73ElDBs

**Comment by gnembon** [comment]
yep - such features should not be implemented as mods. Noone gonna maintain them. Use a script instead and customize it to your liking.
https://github.com/gnembon/scarpet/blob/master/programs/survival/auto_pickup.sc
